"""
email_service.py — Send HTML briefing emails with MP3 attachments via SMTP.
"""
import html
import logging
import smtplib
from email.message import EmailMessage
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

AUDIO_DIR = Path(__file__).parent.parent / "static" / "audio"

_EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #F1F5F9; margin: 0; padding: 0; }}
  .wrapper {{ max-width: 640px; margin: 32px auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 16px rgba(0,0,0,0.08); }}
  .header {{ background: #0C1220; padding: 28px 32px; }}
  .header h1 {{ color: white; font-size: 24px; font-weight: 900; margin: 0; letter-spacing: -0.5px; }}
  .header h1 span {{ color: #60A5FA; }}
  .header p {{ color: #64748B; font-size: 13px; margin: 6px 0 0; }}
  .kpi-row {{ display: flex; gap: 12px; padding: 20px 32px; background: #F8FAFC; border-bottom: 1px solid #E2E8F0; }}
  .kpi {{ flex: 1; text-align: center; }}
  .kpi-val {{ font-size: 20px; font-weight: 700; color: #0F172A; }}
  .kpi-lbl {{ font-size: 11px; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.08em; margin-top: 2px; }}
  .topics {{ padding: 16px 32px; border-bottom: 1px solid #E2E8F0; }}
  .tag {{ display: inline-block; background: #EFF6FF; color: #1D4ED8; border: 1px solid #BFDBFE; border-radius: 5px; padding: 2px 10px; font-size: 12px; font-weight: 500; margin: 2px; }}
  .script-section {{ padding: 24px 32px; }}
  .script-section h2 {{ font-size: 12px; font-weight: 700; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.08em; margin: 0 0 12px; }}
  .script {{ background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 18px 20px; font-size: 14px; color: #1E293B; line-height: 1.75; white-space: pre-wrap; }}
  .analytics-section {{ padding: 0 32px 24px; }}
  .analytics-section h2 {{ font-size: 12px; font-weight: 700; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.08em; margin: 0 0 12px; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 12.5px; }}
  th {{ text-align: left; padding: 8px 10px; background: #F8FAFC; color: #64748B; font-weight: 600; border-bottom: 1px solid #E2E8F0; }}
  td {{ padding: 9px 10px; border-bottom: 1px solid #F1F5F9; color: #374151; vertical-align: top; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 20px; font-size: 11px; font-weight: 600; }}
  .badge-pos {{ background: #ecfdf5; color: #059669; }}
  .badge-neg {{ background: #fef2f2; color: #dc2626; }}
  .badge-neu {{ background: #fffbeb; color: #d97706; }}
  .footer {{ padding: 20px 32px; background: #F8FAFC; text-align: center; font-size: 11px; color: #94A3B8; border-top: 1px solid #E2E8F0; }}
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>Briefly <span>AI</span></h1>
    <p>Your financial briefing &nbsp;·&nbsp; {created_at}</p>
  </div>

  <div class="kpi-row">
    <div class="kpi"><div class="kpi-val">{sources_count}</div><div class="kpi-lbl">Sources</div></div>
    <div class="kpi"><div class="kpi-val">{duration_minutes} min</div><div class="kpi-lbl">Duration</div></div>
    <div class="kpi"><div class="kpi-val">{clusters_count}</div><div class="kpi-lbl">Topics</div></div>
  </div>

  <div class="topics">
    {topics_html}
  </div>

  <div class="script-section">
    <h2>Script</h2>
    <div class="script">{script}</div>
  </div>

  {analytics_section}

  <div class="footer">
    Generated by Briefly AI &nbsp;·&nbsp; Powered by Groq LLaMA 3.3 &amp; gTTS<br>
    The audio version is attached as an MP3 file.
  </div>
</div>
</body>
</html>
"""

_ANALYTICS_SECTION = """\
  <div class="analytics-section">
    <h2>Article Analytics</h2>
    <table>
      <thead><tr><th>Article</th><th>Sentiment</th><th>Urgency</th><th>Impact</th></tr></thead>
      <tbody>{rows}</tbody>
    </table>
  </div>
"""


def _sentiment_badge(sentiment: str) -> str:
    cls = {"Positive": "badge-pos", "Negative": "badge-neg"}.get(sentiment, "badge-neu")
    return f'<span class="badge {cls}">{sentiment}</span>'


def _build_html(briefing: dict) -> str:
    clusters = briefing.get("clusters") or {}
    analytics = briefing.get("analytics") or []
    cluster_list = sorted(clusters.get("clusters", []), key=lambda c: c.get("priority", 99))
    topics_html = " ".join(
        f'<span class="tag">{html.escape(str(c["cluster_name"]))}</span>'
        for c in cluster_list
    )

    analytics_rows = ""
    for r in analytics:
        subject = html.escape(str(r.get("subject") or r.get("one_line_summary", ""))[:60])
        sentiment = html.escape(str(r.get("sentiment", "Neutral")))
        urgency = html.escape(str(r.get("urgency", "—")))
        impact = html.escape(str(r.get("market_impact", "—")))
        analytics_rows += (
            f"<tr><td>{subject}</td>"
            f"<td>{_sentiment_badge(sentiment)}</td>"
            f"<td>{urgency}/10</td>"
            f"<td>{impact}/10</td></tr>"
        )
    analytics_section = _ANALYTICS_SECTION.format(rows=analytics_rows) if analytics_rows else ""

    return _EMAIL_TEMPLATE.format(
        created_at=briefing.get("created_at", "")[:16].replace("T", " "),
        sources_count=briefing.get("sources_count", 0),
        duration_minutes=briefing.get("duration_minutes", 3),
        clusters_count=len(cluster_list),
        topics_html=topics_html or '<span class="tag">Financial News</span>',
        script=html.escape(briefing.get("script", "")),
        analytics_section=analytics_section,
    )


def send_briefing_email(
    briefing: dict,
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    from_address: str,
    to_address: str,
) -> None:
    """Send briefing email with HTML body + MP3 attachment."""
    msg = EmailMessage()
    created = briefing.get("created_at", "")[:16].replace("T", " ")
    msg["Subject"] = f"Your Briefly AI Briefing — {created}"
    msg["From"] = from_address
    msg["To"] = to_address

    # Plain text fallback
    msg.set_content(f"Your Briefly AI briefing for {created}.\n\n{briefing.get('script', '')}")

    # HTML body
    html_body = _build_html(briefing)
    msg.add_alternative(html_body, subtype="html")

    # MP3 attachment
    audio_filename = briefing.get("audio_filename")
    if audio_filename:
        audio_path = AUDIO_DIR / audio_filename
        if audio_path.exists():
            with open(audio_path, "rb") as f:
                msg.add_attachment(
                    f.read(),
                    maintype="audio",
                    subtype="mpeg",
                    filename=f"briefing_{created.replace(' ', '_').replace(':', '')}.mp3",
                )

    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)
    except smtplib.SMTPAuthenticationError:
        logger.error("SMTP authentication failed for user %s", smtp_user)
        raise
    except Exception:
        logger.error("SMTP send failed", exc_info=True)
        raise
